class_name T
extends Node

const PRAYTIMES_NAME: Dictionary = {
	"Asr": "T_NAME_ASR",
	"Dhuhr": "T_NAME_DHUHR",
	"Fajr": "T_NAME_FAJR",
	"Firstthird": "T_NAME_FIRSTTHIRD",
	"Imsak": "T_NAME_IMSAK",
	"Isha": "T_NAME_ISHA",
	"Lastthird": "T_NAME_LASTTHIRD",
	"Maghrib": "T_NAME_MAGHRIB",
	"Midnight": "T_NAME_MIDNIGHT",
	"Sunrise": "T_NAME_SUNRISE",
	"Sunset": "T_NAME_SUNSET"
}

const MONTH_NAME_GREGORIAN: Array = [
	"T_MONTH_G_JANUARY",
	"T_MONTH_G_FEBRUARY",
	"T_MONTH_G_MARCH",
	"T_MONTH_G_APRIL",
	"T_MONTH_G_MAY",
	"T_MONTH_G_JUNE",
	"T_MONTH_G_JULY",
	"T_MONTH_G_AUGUST",
	"T_MONTH_G_SEPTEMBER",
	"T_MONTH_G_OCTOBER",
	"T_MONTH_G_NOVEMBER",
	"T_MONTH_G_DECEMBER",
];

const MONTH_NAME_HIJRI: Array = [
	"T_MONTH_H_MUHARRAM",
	"T_MONTH_H_SAFAR",
	"T_MONTH_H_RABI_AWWAL",
	"T_MONTH_H_RABI_THANI",
	"T_MONTH_H_JUMADA_AWWAL",
	"T_MONTH_H_JUMADA_THANI",
	"T_MONTH_H_RAJAB",
	"T_MONTH_H_SHABAN",
	"T_MONTH_H_RAMADAN",
	"T_MONTH_H_SHAWWAL",
	"T_MONTH_H_DHU_AL_QIDAH",
	"T_MONTH_H_DHU_AL_HIJJAH",
];

const WEEKDAY_NAME_GREGORIAN: Array = [
	"T_WEEKDAY_G_SUNDAY",
	"T_WEEKDAY_G_MONDAY",
	"T_WEEKDAY_G_TUESDAY",
	"T_WEEKDAY_G_WEDNESDAY",
	"T_WEEKDAY_G_THURSDAY",
	"T_WEEKDAY_G_FRIDAY",
	"T_WEEKDAY_G_SATURDAY",
];

const WEEKDAY_NAME_HIJRI: Array = [
	"T_WEEKDAY_H_AHAD",
	"T_WEEKDAY_H_ITHNAYN",
	"T_WEEKDAY_H_THULATHA",
	"T_WEEKDAY_H_ARBAA",
	"T_WEEKDAY_H_KHAMIS",
	"T_WEEKDAY_H_JUMUAH",
	"T_WEEKDAY_H_SABT",
];
